services:
  api-gateway:
    build: ./api_gateway_service
    mem_limit: 400m
    cpus: "1.00"
    ports:
      - "8080:8080"
    environment:
      - PORT=${API_GATEWAY_PORT}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - APPOINTMENT_SERVICE_URL=${APPOINTMENT_SERVICE_URL}
      - DOCTOR_SERVICE_URL=${DOCTOR_SERVICE_URL}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
      - PAYMENT_SERVICE_URL=${PAYMENT_SERVICE_URL}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - RATING_SERVICE_URL=${RATING_SERVICE_URL}
      - SCHEDULE_SERVICE_URL=${SCHEDULE_SERVICE_URL}
      - AI_SERVICE_URL=${AI_SERVICE_URL}
      - MESSAGE_SERVICE_URL=${MESSAGE_SERVICE_URL}
    depends_on:
      - user-service
      - appointment-service
      - doctor-service
      - notification-service
      - payment-service
      - auth-service
      - rating-service
      - schedule-service
      - ai-service
      - message-service
    networks:
      - healthcare_network

  # User service
  user-service:
    build:
      context: ./services/user_service
      dockerfile: Dockerfile
    mem_limit: 300m
    cpus: "0.80"
    ports:
      - "8081:8081"
    env_file:
      - ./services/user_service/.env
    environment:
      - DATABASE_URL=${USER_DATABASE_URL}
    volumes:
      - ./services/user_service:/app:cached
      - user_node_modules:/app/node_modules
      - ./shared:/shared
    networks:
      - healthcare_network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  # Appointment service
  appointment-service:
    build:
      context: ./services/appointment_service
      dockerfile: Dockerfile
    mem_limit: 300m
    cpus: "0.80"
    ports:
      - "8082:8082"
    env_file:
      - ./services/appointment_service/.env
    environment:
      - DATABASE_URL=${APPOINTMENT_DATABASE_URL}
    volumes:
      - ./services/appointment_service:/app:cached
      - appointment_node_modules:/app/node_modules
      - ./shared:/shared
    networks:
      - healthcare_network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  ai-service:
    build:
      context: ./services/ai_service
      dockerfile: Dockerfile
    mem_limit: 300m
    cpus: "0.80"
    ports:
      - "8089:8089"
    env_file:
      - ./services/ai_service/.env
    volumes:
      - ./services/ai_service:/app:cached
      - ai_node_modules:/app/node_modules
      - ./shared:/shared
    networks:
      - healthcare_network
    command: npm run dev

  # Doctor service
  doctor-service:
    build:
      context: ./services/doctor_service
      dockerfile: Dockerfile
    mem_limit: 300m
    cpus: "0.80"
    ports:
      - "8083:8083"
    env_file:
      - ./services/doctor_service/.env
    environment:
      - DATABASE_URL=${DOCTOR_DATABASE_URL}
    volumes:
      - ./services/doctor_service:/app:cached
      - doctor_node_modules:/app/node_modules
      - ./shared:/shared
    networks:
      - healthcare_network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  # Notification service
  notification-service:
    build:
      context: ./services/notification_service
      dockerfile: Dockerfile
    mem_limit: 300m
    cpus: "0.80"
    ports:
      - "8084:8084"
    env_file:
      - ./services/notification_service/.env
    environment:
      - DATABASE_URL=${NOTIFICATION_DATABASE_URL}
    volumes:
      - ./services/notification_service:/app:cached
      - notification_node_modules:/app/node_modules
      - ./shared:/shared
    networks:
      - healthcare_network
    command: npm run dev

  # Payment service
  payment-service:
    build:
      context: ./services/payment_service
      dockerfile: Dockerfile
    mem_limit: 300m
    cpus: "0.80"
    ports:
      - "8085:8085"
    env_file:
      - ./services/payment_service/.env
    environment:
      - DATABASE_URL=${PAYMENT_DATABASE_URL}
    volumes:
      - ./services/payment_service:/app:cached
      - payment_node_modules:/app/node_modules
      - ./shared:/shared
    networks:
      - healthcare_network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  auth-service:
    build:
      context: ./services/auth_service
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 300m
    cpus: "0.80"
    ports:
      - "8086:8086"
    env_file:
      - ./services/auth_service/.env
    environment:
      - DATABASE_URL=${AUTH_DATABASE_URL}
    volumes:
      - ./services/auth_service:/app:cached
      - auth_node_modules:/app/node_modules
      - ./shared:/shared
    networks:
      - healthcare_network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  schedule-service:
    build:
      context: ./services/schedule_service
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 300m
    cpus: "0.80"
    ports:
      - "8088:8088"
    env_file:
      - ./services/schedule_service/.env
    environment:
      - DATABASE_URL=${SCHEDULE_DATABASE_URL}
    volumes:
      - ./services/schedule_service:/app:cached
      - schedule_node_modules:/app/node_modules
      - ./shared:/shared
    networks:
      - healthcare_network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  rating-service:
    build:
      context: ./services/rating_service
      dockerfile: Dockerfile
    mem_limit: 300m
    cpus: "0.80"
    ports:
      - "8087:8087"
    env_file:
      - ./services/rating_service/.env
    environment:
      - DATABASE_URL=${RATING_DATABASE_URL}
    volumes:
      - ./services/rating_service:/app:cached
      - rating_node_modules:/app/node_modules
      - ./shared:/shared
    networks:
      - healthcare_network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  message-service:
    build:
      context: ./services/message_service
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 300m
    cpus: "0.80"
    ports:
      - "9000:9000"
    env_file:
      - ./services/message_service/.env
    environment:
      - DATABASE_URL=${MESSAGE_DATABASE_URL}
    volumes:
      - ./services/message_service:/app:cached
      - message_node_modules:/app/node_modules
      - ./shared:/shared
    networks:
      - healthcare_network
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

# Define networks
networks:
  healthcare_network:
    external: true
    name: medicare_booking_app_healthcare_network

# Define volumes
volumes:
  user_node_modules:
  doctor_node_modules:
  auth_node_modules:
  appointment_node_modules:
  rabbitmq_data:
  schedule_node_modules:
  notification_node_modules:
  payment_node_modules:
  message_node_modules:
  ai_node_modules:
  rating_node_modules:
